# Generated by Django 3.2.16 on 2022-11-30 14:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='课程名')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacherinfo')),
            ],
            options={
                'unique_together': {('name', 'teacher_id')},
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('major_code', models.CharField(max_length=32, unique=True, verbose_name='专业代码')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='专业名')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
            ],
        ),
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='班级名')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
                ('major_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.major')),
            ],
            options={
                'unique_together': {('name', 'major_id')},
            },
        ),
        migrations.CreateModel(
            name='StudentCurriculumScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=1, max_digits=10)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
                ('curriculum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.curriculum')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
            ],
            options={
                'unique_together': {('student_id', 'curriculum_id')},
            },
        ),
        migrations.CreateModel(
            name='SchoolTimeTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('clazz_week', models.CharField(choices=[(1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五')], max_length=32, verbose_name='周几的课')),
                ('clazz_time', models.CharField(choices=[(1, '8:00~9:40'), (2, '10:00~11:40'), (3, '14:00~15:40'), (4, '15:50~17:50')], max_length=32, verbose_name='上课时间')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
                ('clazz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.clazz')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.curriculum')),
            ],
            options={
                'unique_together': {('clazz_week', 'clazz_time', 'clazz_id')},
            },
        ),
        migrations.CreateModel(
            name='ClazzStudents',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='保存日期')),
                ('update_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改日期')),
                ('clazz_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.clazz')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
            ],
            options={
                'unique_together': {('student_id', 'clazz_id')},
            },
        ),
    ]
